name: Tests # names pipeline

on: # wake up this pipeline on push,pull 
  push:
  pull_request:

jobs:
  test: # run tests in ubuntu environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #github premade wrapper (clones the repo and pass it to VE)
      - name: Set up Python
        uses: actions/setup-python@v5 # setup the version of desired python
        with: 
          python-version: "3.13"
      - name: Install Dependencies
        run: | #(about to write multiple line script) upgrade pip -> install requirments -> install pytest
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
            pip install pytest 
      - name: Run Tests 
        run: pytest -vv 