name: Tests # names pipeline 

on: # wake up this pipeline on push,pull
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test: # run tests in ubuntu environment
    runs-on: ubuntu-latest
    services:
      postgres: # launch postgres image 17
        image: postgres:17
        env: # add credentians to postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: python_backend_test
        ports:
          - 5433:5432
        options: >- #command line arguments health check ever 10s
          --health-cmd="pg_isready -U postgres -d python_backend_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis: # create redis image setup port person health checks
        image: redis:7
        ports:
          - 6380:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5 

    steps:

      - uses: actions/checkout@v4 #github premade wrapper (clones the repo and pass it to VE)
      - name: Set up Python
        uses: actions/setup-python@v5 # setup the version of desired python
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: | #(about to write multiple line script) upgrade pip -> install requirments -> install pytest
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Install Postgre Client # install some postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check PostgreSQL
        env:
          PGPASSWORD: postgres
        run: | # check postgres
          pg_isready -h 127.0.0.1 -p 5433 -U postgres -d python_backend_test
          psql -h 127.0.0.1 -p 5433 -U postgres -d python_backend_test -c "SELECT version();"
      - name: Create Database Scheme # create the schema pass by passing init.sql
        env:
          PGPASSWORD: postgres
        run: |
          psql -h 127.0.0.1 -p 5433 -U postgres -d python_backend_test -f Database/init.sql 

      - name: Run Tests
        env: # give env credentials because calling pytest
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5433/python_backend_test
          # Or if your app reads individual variables:
          DB_HOST: 127.0.0.1
          DB_PORT: 5433
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: python_backend_test
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest -vv
      - name: Build, Athenticate and Push Docker Image # get secret token from github and login to ghcr.io with ur user without mirroring it in the terminal then docker tag gives it a link of latest finally push 
        run:  |
             docker build -t task-manager-api . 
             echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u raphael00110 --password-stdin 
             docker tag task-manager-api ghcr.io/raphael00110/task-manager-api:latest
             docker push ghcr.io/raphael00110/task-manager-api:latest



